export default function normalizationHeader({
  generator,
  schemaVersion = "v1.0 Enhanced",
  source
}) {
  const date = new Date().toISOString().split("T")[0];

  return `// AUTO-GENERATED FILE — DO NOT EDIT BY HAND
// Generated by ${generator}
// Schema: ${schemaVersion}
${source ? `// Source: ${source}\n` : ""}// Generated: ${date}

`;
}
